# Конфигурация NLP модулей для переписывания текстов
nlp:
  # Основные настройки
  language: "russian"
  max_text_length: 5000
  min_text_length: 10
  
  # Модели и ресурсы
  models:
    spacy_model: "ru_core_news_lg"
    synonym_model: "models/nlp_models/synonym_model"
    paraphrase_model: "models/nlp_models/paraphrase_model"
    
  # Настройки переписывания
  rewriting:
    synonym_replacement_rate: 0.7
    sentence_reorder_rate: 0.5
    structure_change_rate: 0.8
    preserve_technical_terms: true
    min_meaning_preservation: 0.8
    max_attempts_per_text: 3
    
  # Сохранение терминов
  preserved_terms:
    technical_specs: true
    brands: true
    models: true
    measurements: true
    materials: true
    numbers: true
    units: true
    
  # Списки сохранения
  term_lists:
    brands:
      - "samsung"
      - "apple"
      - "xiaomi"
      - "huawei"
      - "lenovo"
      - "asus"
      - "acer"
      - "dell"
      - "hp"
      - "sony"
      
    technical_terms:
      - "процессор"
      - "оперативная память"
      - "жесткий диск"
      - "ssd"
      - "видеокарта"
      - "монитор"
      - "разрешение"
      - "частота"
      - "емкость"
      - "скорость"
      
    measurement_units:
      - "мм"
      - "см"
      - "м"
      - "кг"
      - "г"
      - "л"
      - "мл"
      - "Гц"
      - "Вт"
      - "В"
      
  # Синонимизация
  synonymization:
    use_contextual_synonyms: true
    max_synonym_length_diff: 2
    preserve_word_forms: true
    exclude_short_words: true
    min_word_length: 3
    
  # Грамматика и стиль
  grammar:
    fix_grammar_errors: true
    preserve_punctuation: true
    normalize_spaces: true
    remove_special_chars: true
    
  # Валидация результатов
  validation:
    check_grammar: true
    check_meaning: true
    check_readability: true
    min_readability_score: 0.6
    max_similarity_threshold: 0.9
    
  # Производительность
  performance:
    batch_size: 10
    max_workers: 4
    cache_size: 1000
    preload_models: true

# Словари синонимов
synonym_dictionaries:
  general: "data/input/synonym_dictionaries/general_synonyms.json"
  technical: "data/input/synonym_dictionaries/technical_terms.json"
  ecommerce: "data/input/synonym_dictionaries/ecommerce_terms.json"
  
  # Автоматическое обновление словарей
  auto_update: true
  update_interval_days: 7

# Расширенные настройки
advanced:
  use_neural_paraphrasing: false
  neural_model_threshold: 0.8
  fallback_to_rules: true
  log_rewriting_decisions: false
